### ISSUE TITLE
（发错了）术士的法术列表是邪术师的

### ISSUE THREAD

**Issue by MrHorse055** [fvtt-cn/5e_chn#4]
合集里，术士的法术列表打开后显示的是邪术师的法术列表。
术士法表里有魔能爆也太离谱了

搞错mod了，非常抱歉

**Comment by collectsand** [comment]
什么消愁哈哈哈🤡👈🤣

**Comment by MrHorse055** [comment]
😡😡😡😡
马上开盒到你家门口






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fvtt-cn/5e_chn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 下午2:12
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [fvtt-cn/5e_chn] （发错了）术士的法术列表是邪术师的 (Issue #4)





 
什么消愁哈哈哈🤡👈🤣
